version: "3.8"

services:
    web:
        build: .
        container_name: django
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn -b 0.0.0.0:8000 source.wsgi --reload"
        volumes:
            - .:/app
            - media:/app/media/
            - static:/app/static/
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres:latest
        container_name: pgdb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=kabarmedia
        - POSTGRES_USER=kabarmedia
        - POSTGRES_PASSWORD=kabarmedia
    nginx:
        image: linuxserver/swag
        restart: always
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Bishkek
            - URL=kabar-media.kg
            - SUBDOMAINS=api
            - VALIDATION=http
            - ONLY_SUBDOMAINS=true
            - STAGING=false
        depends_on:
            - web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/default.conf:/config/nginx/site-confs/default
            - media:/usr/media/
            - lets:/config/keys/
            - static:/usr/static/
volumes:
  postgres_data:
  static:
  media:
  lets: