# Generated by Django 3.2.9 on 2022-01-16 14:13

import apps.articles.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('link', models.URLField(verbose_name='Ссылка на заказчика')),
                ('image', models.ImageField(upload_to='advertising/', verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Тело поста')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главный пост')),
                ('is_interesting', models.BooleanField(default=False, verbose_name='Интересное?')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id объекта медиа')),
                ('viewed', models.PositiveIntegerField(blank=True, default=0, verbose_name='Просмотрено')),
                ('region', models.PositiveSmallIntegerField(choices=[(1, 'Ош'), (2, 'Чуй'), (3, 'Жалал-Абад'), (4, 'Баткен'), (5, 'Иссык-Куль'), (6, 'Нарын'), (7, 'Талас')], verbose_name='Область/Регион')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(max_length=255, verbose_name='Инстаграм')),
                ('telegram', models.URLField(max_length=255, verbose_name='Телеграм')),
                ('youtube', models.URLField(max_length=255, verbose_name='Ютуб')),
                ('facebook', models.URLField(max_length=255, verbose_name='Фейсбук')),
            ],
            options={
                'verbose_name': 'Медиа ссылка',
                'verbose_name_plural': 'Медиа ссылки',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Видео')),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/', validators=[apps.articles.validators.validate_file_extension], verbose_name='Загружаемое видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Превью для видео')),
            ],
            options={
                'verbose_name': 'Новость с Видео',
                'verbose_name_plural': 'Новости с Видео',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='Изображение')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Новость с Изображением',
                'verbose_name_plural': 'Новости с Изображением',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('image', 'video')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Изображение/Видео'),
        ),
        migrations.CreateModel(
            name='ArticleMainProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Главная новость',
                'verbose_name_plural': 'Главная новость',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.article',),
        ),
    ]
