# Generated by Django 3.2.9 on 2022-01-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('articles', '0003_alter_image_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('video',)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Изображение/Видео'),
        ),
        migrations.AlterField(
            model_name='image',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article', verbose_name='Новость'),
        ),
    ]
