# Generated by Django 3.2.9 on 2022-01-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220116_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='news',
        ),
    ]
